### PR TITLE
Statblock linked markdown

### PR DESCRIPTION
**Pull request by abaddon01**
Modifies 3 Files
* Spells.md 
- Full spell list, Reformatted markdown aimed at Obsidian use - with an emphasis on linkign from otehr fiels
* Class-Spells.md
- Reformatted markdown aimed at Obsidian use - cross- references spells in Spells.md for added detail
* feats.md
- Reformatted markdown aimed at Obsidian use - keeps index - maintains data structure 

Adds 1 File
* Fantasy Statblock Monster file.json
- A JSON file that holds a first cut at fantasy statblock formatted monsters from the SRD html files.
  - Ready for importing into fantasy stablock via "import generic data"
  - Formatted for a custom 3.5e layout - should work with default 5e layout

### CODE REVIEW

**Comment by sigrunixia** [comment]
It's been real busy at work this week. I should be able to carve out some time to fully review the PR this weekend. :)

**Review by sigrunixia — APPROVED** [review]

**Comment by sigrunixia** [comment]
Are you ready to merge?

**Comment by abaddon01** [comment]
Yep, ready to merge.

**Comment by sigrunixia** [comment]
Merged in! Thank you!

**Pull request merged**
